### PR TITLE
updated doc of swiss roll notebook accordingly.

### PR DESCRIPTION
**Pull request by ralfbanisch**
I think this last commit didn't make it into master.

### CODE REVIEW

**Comment by ehthiede** [comment]
It didn't.  It's actually somewhat duplicated i

**Comment by ralfbanisch** [comment]
What do you mean?

-Ralf

**Comment by ehthiede** [comment]
My line of thought was that if we had accidentally pushed a broken example to the python repository, we might have to release a patch.  Fortunately, what happened is that both you and I made the general change (changing mydmap.epsilon to mydmap.epsilon_fitted) twice.  Since this happened before release, we don't need to release a patch.  We just merge dev into master, and then continue developing.

**Comment by ralfbanisch** [comment]
what needs to be done here? Merge or close?

**Comment by ehthiede** [comment]
Close should be fine.

-Erik

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
